{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "session-backend.fullname" . }}
  labels:
    {{- include "session-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "session-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "session-backend.postgresql.fullname" . }}
  labels:
    {{- include "session-backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "session-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "session-backend.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: api
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
