{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-backend.postgresql.fullname" . }}
  labels:
    {{- include "session-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "session-backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
