{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "session-backend.postgresql.fullname" . }}
  labels:
    {{- include "session-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
