apiVersion: v1
kind: Service
metadata:
  name: {{ include "session-backend.fullname" . }}
  labels:
    {{- include "session-backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.sessionBackend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.sessionBackend.service.type }}
  ports:
    - port: {{ .Values.sessionBackend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "session-backend.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
